### ISSUE TITLE
Latest update causes no work to get done

### ISSUE THREAD

**Issue by sayheyjay** [fluffy-mods/WorkTab#128]
**Describe the bug**  
Following latest update on Steam, pawns start work at workbenches but either freeze or stop working with no output.

**Expected behavior**  
Prior to update everything worked.

**Steps to reproduce**  

1. Have a pawn use a workbench (eg lumber mill)
2. 
3.

**Other mods**  
Too many, see below

**Output log**  
https://gist.github.com/3caef2d43a3ec1c0edfab1434efadfe5

**Save game**  
https://1drv.ms/u/s!AtDbxtgwtJIAgjhcU4-gEz26k4rA?e=h3EqJQ

**Environment**  
 - OS: Mac
 - 64
 
**Game**
 - 64 bits
 - Steam
 - Version - latest

**Comment by FluffierThanThou** [comment]
This appears to be related to the _Fermenter_ mod by Pelador. 
https://steamcommunity.com/sharedfiles/filedetails/?id=1922837421

Below are the steps I've taken to triage the issue, if you're somewhat comfortable around a stack trace, it might be helpful to resolve future issues yourself 👍. (Not that I mind, just trying to be helpful).

The error is;
```
Exception in JobDriver tick for pawn Frony driver=JobDriver_DoBill (toilIndex=24) driver.job=(DoBill (Job_2363076) A=Thing_TableWoodworking357254 B=Thing_WoodLog_Oak1526999 C=(197, 0, 189)) lastJobGiver=RimWorld.JobGiver_Work
System.NullReferenceException: Object reference not set to an instance of an object
at (wrapper dynamic-method) RimWorld.Bill.Notify_PawnDidWork_Patch1 (object,Verse.Pawn) <0x00000>
at Verse.AI.Toils_Recipe/<DoRecipeWork>c__AnonStorey1.<>m__1 () <0x00197>
at (wrapper dynamic-method) Verse.AI.JobDriver.DriverTick_Patch1 (object) <0x003e8>
```

Which is raised from `RimWorld.Bill.Notify_PawnDidWork_Patch1`. 

If we search for anything that patches `RimWorld.Bill.Notify_PawnDidWork`, we find the `CookOil` dll, specifically this postfix: `CookOil.Notify_PawnDidWork_Patch.PostFix`. Further searching for `CookOil` reveals that it uses the harmony instance id `com.Pelador.Rimworld.CookOil`. A quick google search leads us to Pelador's `Fermenter`: https://steamcommunity.com/sharedfiles/filedetails/?id=1922837421.

P.S. On a side note, Work Tab _does not_, _will never_ and _has never_ made any changes to the actual jobs that are performed. It _only_ opens up the existing priority system for more fine-grained changes. Any issues you run into with particular jobs are therefore _extremely unlikely_ to be caused by Work Tab.
